# Generated by Django 2.1 on 2019-05-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='location',
        ),
    ]
