# Generated by Django 2.1 on 2019-05-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
